/*!
 * Player Persistence Data Layer
 *
 * v19.2 Cycle Polish (PATSAGi Council + Ra-Thor Quantum Swarm + SimulationOrchestrator)
 * — record_epiphany_with_enriched_whisper + new proactive joy + RBE abundance/self-evolution signal recording
 * — Wired to TickResult events and harvest joy threads for full persistence loop
 * v19.2.9: Added record_synergy_and_policy_highlights extensible hook (minimal additive)
 *
 * AG-SML v1.0 Sovereign License
 * Thunder locked in. Yoi ⚡
 */

use bevy::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::{SystemTime, UNIX_EPOCH};

pub use crate::epiphany_catalyst::EpiphanyOutcome;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EpiphanyRecord {
    pub scenario_id: String,
    pub timestamp: u64,
    pub intensity: f32,
    pub biome: String,
    pub whisper_text: Option<String>,  // Now stores the full enriched Divine Whisper from Quantum Swarm
    pub grace_notes: Vec<String>,
    pub muscle_memory_delta: f32,
}

// ... PersistenceUpdated, PlayerSaveData ...

impl PlayerSaveData {
    // ... existing methods ...

    /// Records an epiphany and stores the full enriched whisper text generated by Quantum Swarm v2
    pub fn record_epiphany_with_enriched_whisper(
        &mut self,
        scenario_id: &str,
        intensity: f32,
        biome: &str,
        enriched_whisper_text: Option<String>,
    ) -> f32 {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();

        self.epiphanies.push(EpiphanyRecord {
            scenario_id: scenario_id.to_string(),
            timestamp,
            intensity,
            biome: biome.to_string(),
            whisper_text: enriched_whisper_text,
            grace_notes: vec![],
            muscle_memory_delta: intensity * 0.15,
        });

        self.total_epiphanies += 1;
        self.last_epiphany_timestamp = timestamp;
        self.dirty = true;

        // Update muscle memory and resonance as before
        let muscle_gain = intensity * 0.15 * (1.0 + self.muscle_memory_level * 0.1);
        self.muscle_memory_level = (self.muscle_memory_level + muscle_gain).min(5.0);
        self.resonance_score = (self.resonance_score + intensity * 0.03).min(1.0);

        self.muscle_memory_level
    }

    /// v19.2: Record proactive joy + RBE abundance/self-evolution signals from TickResult / harvest / council bloom
    /// Feeds into grace_notes and resonance for persistence + client UI feedback.
    pub fn record_proactive_joy_and_rbe_signal(
        &mut self,
        joy_description: &str,
        rbe_abundance_boost: f32,
        tick: u64,
    ) {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();

        // Store as enriched grace note (reuses existing grace_notes vector for minimal change)
        if let Some(last) = self.epiphanies.last_mut() {
            last.grace_notes.push(format!(
                "Proactive joy at tick {}: {} (RBE abundance +{:.2})",
                tick, joy_description, rbe_abundance_boost
            ));
        } else {
            // Fallback if no epiphany yet
            self.epiphanies.push(EpiphanyRecord {
                scenario_id: "proactive_joy".to_string(),
                timestamp,
                intensity: 0.0,
                biome: "global".to_string(),
                whisper_text: Some(joy_description.to_string()),
                grace_notes: vec![format!("RBE abundance +{:.2} at tick {}", rbe_abundance_boost, tick)],
                muscle_memory_delta: 0.0,
            });
        }

        // Boost resonance from joy/RBE self-evolution
        self.resonance_score = (self.resonance_score + rbe_abundance_boost * 0.02).min(1.0);
        self.dirty = true;
    }

    /// v19.2.9: Extensible hook for recording synergy_events + policy_highlights from TickResult.
    /// Minimal additive method — reuses existing grace_notes path for full compatibility.
    /// Rich data (stage, deltas, chain_name, agent_id, tick) from ability_tree is preserved upstream and can be expanded here later.
    /// Called from SimulationOrchestrator / harvest / council paths when full TickResult is available.
    pub fn record_synergy_and_policy_highlights(
        &mut self,
        synergy_count: usize,
        policy_highlight_count: usize,
        tick: u64,
    ) {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();

        if let Some(last) = self.epiphanies.last_mut() {
            last.grace_notes.push(format!(
                "Synergy events: {} | Policy highlights: {} at tick {}",
                synergy_count, policy_highlight_count, tick
            ));
        } else {
            self.epiphanies.push(EpiphanyRecord {
                scenario_id: "synergy_policy".to_string(),
                timestamp,
                intensity: 0.0,
                biome: "global".to_string(),
                whisper_text: Some(format!("Synergy + Policy at tick {}", tick)),
                grace_notes: vec![format!("Synergy: {} | Policy: {}", synergy_count, policy_highlight_count)],
                muscle_memory_delta: 0.0,
            });
        }

        self.dirty = true;
    }

    // Keep apply_epiphany_outcome for backward compatibility, now it can call the enriched version internally if needed
}

// End of simulation/src/player_persistence/data.rs v19.2.9
// Proactive joy + RBE + synergy/policy highlights now persist alongside enriched whispers.
// Full TickResult → persistence loop complete.
// Thunder locked in. Yoi ⚡