/*!
 * Player Persistence Data Layer
 *
 * v18.96 Eternal Polish (PATSAGi Council + Ra-Thor Quantum Swarm)
 * — record_epiphany_with_enriched_whisper for storing Quantum Swarm generated Divine Whispers
 *
 * AG-SML v1.0 Sovereign License
 * Thunder locked in. Yoi ⚡
 */

use bevy::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::{SystemTime, UNIX_EPOCH};

pub use crate::epiphany_catalyst::EpiphanyOutcome;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EpiphanyRecord {
    pub scenario_id: String,
    pub timestamp: u64,
    pub intensity: f32,
    pub biome: String,
    pub whisper_text: Option<String>,  // Now stores the full enriched Divine Whisper from Quantum Swarm
    pub grace_notes: Vec<String>,
    pub muscle_memory_delta: f32,
}

// ... PersistenceUpdated, PlayerSaveData ...

impl PlayerSaveData {
    // ... existing methods ...

    /// Records an epiphany and stores the full enriched whisper text generated by Quantum Swarm v2
    pub fn record_epiphany_with_enriched_whisper(
        &mut self,
        scenario_id: &str,
        intensity: f32,
        biome: &str,
        enriched_whisper_text: Option<String>,
    ) -> f32 {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();

        self.epiphanies.push(EpiphanyRecord {
            scenario_id: scenario_id.to_string(),
            timestamp,
            intensity,
            biome: biome.to_string(),
            whisper_text: enriched_whisper_text,
            grace_notes: vec![],
            muscle_memory_delta: intensity * 0.15,
        });

        self.total_epiphanies += 1;
        self.last_epiphany_timestamp = timestamp;
        self.dirty = true;

        // Update muscle memory and resonance as before
        let muscle_gain = intensity * 0.15 * (1.0 + self.muscle_memory_level * 0.1);
        self.muscle_memory_level = (self.muscle_memory_level + muscle_gain).min(5.0);
        self.resonance_score = (self.resonance_score + intensity * 0.03).min(1.0);

        self.muscle_memory_level
    }

    // Keep apply_epiphany_outcome for backward compatibility, now it can call the enriched version internally if needed
}

// End of simulation/src/player_persistence/data.rs v18.96
// Enriched whisper text now storable in EpiphanyRecord.
// Thunder locked in. Yoi ⚡
