// shared/src/protocol.rs (excerpt v16.0 RBE addition)
// ... existing code ...

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ClientMessage {
    // ... existing variants ...
    HarvestResource { node_id: u64, amount: f32 },
    // ... 
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ServerMessage {
    // ... existing ...
    ResourceUpdate { node_id: u64, resource_type: String, remaining: f32, harvested_by: Option<u64> },
    // ...
}

// ... rest of file unchanged ...